# Generated by Django 5.1.1 on 2024-09-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mecánico'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('reparado', 'Reparado'), ('no_reparado', 'No reparado')], default='no_reparado', max_length=12),
        ),
    ]
