# Generated by Django 5.1.1 on 2024-09-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_vehiculo_reparacion_vehiculo_cita_mecanico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.mecánico'),
        ),
    ]
