# Generated by Django 5.1.1 on 2024-09-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_mecanico_alter_cita_options_alter_reparacion_options_and_more'),
    ]

    operations = [
    ]
